/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheinBonusRouteImport } from './routes/shein-bonus'
import { Route as IndexRouteImport } from './routes/index'

const SheinBonusRoute = SheinBonusRouteImport.update({
  id: '/shein-bonus',
  path: '/shein-bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shein-bonus': typeof SheinBonusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shein-bonus': typeof SheinBonusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shein-bonus': typeof SheinBonusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shein-bonus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shein-bonus'
  id: '__root__' | '/' | '/shein-bonus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SheinBonusRoute: typeof SheinBonusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shein-bonus': {
      id: '/shein-bonus'
      path: '/shein-bonus'
      fullPath: '/shein-bonus'
      preLoaderRoute: typeof SheinBonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SheinBonusRoute: SheinBonusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
